services:
  - type: web
    name: aviansense-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn fyp_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: PYTHON_VERSION
        value: "3.13.3"
      - key: CLOUDINARY_URL
        sync: false
