# Generated by Django 6.0.2 on 2026-02-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='source',
            field=models.CharField(default='ai', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='status',
            field=models.CharField(default='Alert', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diagnosis_images/'),
        ),
    ]
