# Generated by Django 6.0.2 on 2026-03-31 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_dailytask_supplier_chatroom_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='fcm_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.CreateModel(
            name='MortalityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=1)),
                ('cause', models.CharField(choices=[('disease', 'Disease'), ('unknown', 'Unknown'), ('accident', 'Accident'), ('heat', 'Heat Stress'), ('cold', 'Cold Stress')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_logs', to='api.farm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dosage', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='api.diagnosisresult')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='api.farm')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('vaccine_name_ur', models.CharField(blank=True, default='', max_length=255)),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('flock_age_days', models.IntegerField(default=0)),
                ('dose_count', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='api.farm')),
            ],
            options={
                'ordering': ['-date_administered'],
            },
        ),
    ]
