# Generated by Django 6.0.2 on 2026-04-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_marketrateoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketrateoverride',
            name='region_key',
            field=models.CharField(choices=[('punjab', 'Punjab (Market Committee official rate)')], db_index=True, default='punjab', max_length=32),
        ),
    ]
