# Generated by Django 6.0.2 on 2026-04-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_marketrateoverride_region_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketrateoverride',
            name='doc_price',
        ),
    ]
